# netlify.toml
# Configuração completa para uma aplicação Remix no Netlify
# Assumindo Remix com Vite e uso de Netlify Edge Functions

[build]
  command = "remix vite:build"
  publish = "build/client"
  # base = "/" # Descomente e ajuste se necessário
  # ignore = "git diff --quiet HEAD^ HEAD." # Exemplo de comando para ignorar builds

[functions]
  directory = "netlify/functions"
  # node_bundler = "esbuild"

[[redirects]]
  from = "/antigo-url-pagina"
  to = "/novo-url-pagina"
  status = 301

[[redirects]]
  from = "/em-manutencao"
  to = "/status-page"
  status = 302

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://api.seuservicoexterno.com/:splat"
  status = 200
  # headers = { X-Custom-Header = "Valor" }
  # signed = "API_SECRET_KEY"

[[redirects]]
  from = "/produto"
  to = "/produto-br"
  status = 302
  conditions = { Country = ["BR"] }

[[redirects]]
  from = "/produto"
  to = "/product-us"
  status = 302
  conditions = { Country = ["US"] }

[[redirects]]
  from = "/nao-existe"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.example.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://api.example.com;"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
